name: Sync Docker Images to Aliyun Registry

on:
  push:
    paths:
      - "images.txt"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq

      - name: Parse new images
        id: parse
        run: |
          NEW_IMAGES=$(git diff --unified=0 HEAD^ HEAD -- images.txt | grep '^+[^+]' | cut -c2- | xargs)
          echo "new_images=$NEW_IMAGES" >> $GITHUB_OUTPUT

      - name: Login to Aliyun Registry
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_USERNAME }} --password-stdin ${{ vars.ALIYUN_REGISTRY_URL }}

      - name: Sync images using skopeo
        if: steps.parse.outputs.new_images != ''
        run: |
          for image in ${{ steps.parse.outputs.new_images }}; do
            dest_image="${{ vars.ALIYUN_REGISTRY_URL }}/${{ vars.ALIYUN_REGISTRY_NAMESPACE }}/$image"
            echo "Syncing $image -> $dest_image"
            skopeo copy docker://$image docker://$dest_image --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
          done
